apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartreview-hpa
  namespace: mlops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartreview-api
  minReplicas: 1    # ← réduit de 2 à 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
