name: MLOps Production Pipeline CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AWS_REGION:     eu-west-3
  ECR_REPOSITORY: mlops-expert-api
  EKS_CLUSTER:    mlops-dev
  ACCOUNT_ID:     "718100329950"
  ROLE_ARN:       arn:aws:iam::718100329950:role/github-actions-role-dev

jobs:

  # Job 1 : Tests 
  test:
    name: Tests API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer dépendances
        run: pip install -r api/requirements.txt pytest httpx

      - name: Lancer les tests
        run: |
          cd api
          pytest tests/ -v

  # Job 2 : Terraform Validate 
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform Validate dev
        working-directory: environments/dev
        run: |
          terraform init -backend=false
          terraform validate

  # Job 3 : Build & Push Docker
  build-push:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    needs: [test, terraform-validate]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Générer le tag image
        id: meta
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Télécharger le modèle depuis S3
        run: |
          aws s3 cp \
            s3://mlops-expert-artifacts-dev/models/smartreview/model.tar.gz \
            model.tar.gz
          mkdir -p api/model
          tar -xzf model.tar.gz -C api/model/
          ls -la api/model/      

          
      - name: Build et Push
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            --sbom=false \
            --push \
            -t ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ steps.meta.outputs.tag }} \
            api/

  # Job 4 : Deploy dev 
  deploy-dev:
    name: Deploy dev
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/develop'

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configurer kubeconfig EKS
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.EKS_CLUSTER }} \
            --region ${{ env.AWS_REGION }}

      - name: Déployer sur EKS dev
        run: |
          kubectl set image deployment/smartreview-api \
            api=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ needs.build-push.outputs.image_tag }} \
            -n mlops
          kubectl rollout status deployment/smartreview-api -n mlops --timeout=300s

      - name: Vérifier le déploiement
        run: |
          kubectl get pods -n mlops
          kubectl get svc -n mlops

  # Job 5 : Deploy prod 
  deploy-prod:
    name: Deploy prod
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/main'
    environment: prod

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configurer kubeconfig EKS prod
        run: |
          aws eks update-kubeconfig \
            --name mlops-prod \
            --region ${{ env.AWS_REGION }}

      - name: Déployer sur EKS prod
        run: |
          kubectl set image deployment/smartreview-api \
            api=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ needs.build-push.outputs.image_tag }} \
            -n mlops
          kubectl rollout status deployment/smartreview-api -n mlops --timeout=300s